#!/bin/sh

export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1

/home/ss/Binaries/teamredminer-v0.8.1-linux/teamredminer -o stratum+tcp://us1.ethermine.org:4444 $(cat /home/ss/Development/crypto-applets/configs/ethereum)

