#!/bin/sh

export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1

if /home/ss/Binaries/Cryptocurrencies/profit_mgr.py; then
	/home/ss/Binaries/teamredminer-v0.8.1-linux/teamredminer -o stratum+tcp://us1.ethermine.org:4444 $(cat /home/ss/Development/crypto-applets/configs/ethereum)
	
else
    echo not profitable to mine now
fi
