#!/bin/sh

export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1

/home/ss/Binaries/teamredminer-v0.8.1-linux/teamredminer -o stratum+tcp://daggerhashimoto.usa-east.nicehash.com:3353 $(cat /home/ss/Development/crypto-applets/configs/ethereum) --user=3CdoWz7F3RwtGSiKFf3rCUfatjyyeLy8r5

